name: Deploy to Amazon ECS

on:
  push:
    branches: [ "dev" ]

env:
  AWS_REGION: us-east-1

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}


# Search Github action > marketplace terraform
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
      with:
        terraform_version: v1.12.2
 
    - name: Run terraform Init
      run: | 
        terraform init
 
    - name: Run terraform Validate
      run: | 
        terraform validate
 
    - name: Run terraform Plan
      run: | 
        terraform plan -out=tfplan.txt

# Search Github action > marketplace upload artifact
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: tfplan
        path: tfplan.txt